name: MegaVerse
version: '1.0.1-RELEASE'
main: me.drawn.MegaVerse
author: Drawn
api-version: 1.16

commands:
  megaverse:
    description: "Main plugin command"
    permission: "megaverse.command"
    aliases:
      - mv
      - verseworld
      - world